server:
  port: 8080

spring:
  datasource:
    # ប្តូរពី 192.168.0.120 មកជា localhost
    url: jdbc:postgresql://localhost:5432/codingdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true